### PR TITLE
Translate ‘Happy Birthday’ project in French

### PR DESCRIPTION
**Pull request by lucasfrey**
Hello guys,

Here is my translation for the Happy Birthday project. Let me know if you guys are interested in more  traslation, I am happy to do them all.

### CODE REVIEW

**Comment by rik-cross** [comment]
Hi @lucasfrey - thank you so much for your translation, and thank you for offering to translate more of our projects! Your project will be live on the site within 24 hours.

I'll let @Matella15 (who manages translations) know that you are happy to provide more, and she will let you know our translation priorities. Thanks again!

Rik.

**Comment by Matella15** [comment]
Hi @lucasfrey. Thanks for your translation! It is now up on our [website](http://projects.codeclubworld.org/fr-FR/05_html_01/01/Joyeux%20Anniversaire.html).

It would be great to have your support to translate more projects into French. We are currently pushing to get as many of our projects translated into French as soon as possible. Are you able to work through the rest of the HTML term 1? It would also be great to get your email, so I can intro you to Code Club France and tell them you're working on translations.

**Comment by lucasfrey** [comment]
Hi @Matella15,

Great ! thanks for that.

I am finishing the 'Wanted' project at the moment, just need to get the images translated as well.
I'll try to continue through the rest of the HTML term 1 after that.

You can use the email I got in my Github profile to contact me.

**Comment by Matella15** [comment]
Sounds great @lucasfrey! I'll intro you to our French partners now.

**Pull request merged**
