### PR TITLE
Update Google Fonts instructions for 'Mystery Letter' to cope with UI updates

### PR DESCRIPTION
**Pull request by rtyley**
https://fonts.google.com/ seems to have been updated (at least a year ago, according to the Wayback Machine) and now has a fairly different flow to get to the information you want about how to use
the fonts - ie there's no more 'Quick-use' button, as described in  the previous instructions.

image

I spent ages looking for the 'Quick-use' when trying to follow this lesson plan, until eventually realising I just needed to click on the 'plus' icon!

### CODE REVIEW

**Comment by rik-cross** [comment]
Thanks for making this update @rtyley :)

**Comment by rtyley** [comment]
Thanks @rik-cross - I see that https://codeclubprojects.org/en-GB/webdev/mystery-letter/ is still showing the old screenshots, is there some additional step that must be taken to publish the update?

**Comment by rik-cross** [comment]
@rtyley You're right -- the changes won't be live until I've rebuilt the projects site. I should have time to do that this week.

**Comment by rtyley** [comment]
Any chance this could be pushed out to the live site? Particularly the PDFs?

**Comment by rik-cross** [comment]
Hi @rtyley 

Sorry -- I did rebuild the site a while back but hadn't spotted that the changes had been made to the master branch.

The codeclubprojects.org site is actually built from the [new-layout branch](https://github.com/RaspberryPiFoundation/webdev-curriculum/tree/new-layout). Are you able to update this branch? I can then build the site and the changes will be live.

**Comment by rtyley** [comment]
> The codeclubprojects.org site is actually built from the new-layout branch. Are you able to update this branch?

Done with https://github.com/RaspberryPiFoundation/webdev-curriculum/pull/123 :sparkles:

**Comment by rik-cross** [comment]
Thank you, and sorry for any confusion.

**Pull request merged**
