### PR TITLE
Translate the ‘Recipe’ project in French

### PR DESCRIPTION
**Pull request by lucasfrey**

### CODE REVIEW

**Comment by rik-cross** [comment]
Thanks @lucasfrey 👍

**Comment by Matella15** [comment]
Hey @lucasfrey, we're speaking to a few volunteers about doing some urgent French project translation work in the next week or so. Would you be able to help?

**Comment by lucasfrey** [comment]
Heya @Matella15,

Yeah I should be able to find some time for translation work next week. What are you guys looking for ?

**Comment by Matella15** [comment]
Thanks @lucasfrey, that's great news. We'd be looking for you to work on one or two Python projects - we're just finalising details with a couple of other volunteers but we should be able to tell you which projects we'd need your help with tomorrow. 
Would I be able to get an email address for you in the meantime? No need to post publicly- you can email me directly on katherine@raspberrypi.org if you prefer.

**Pull request merged**
