### PR TITLE
Translate project ’Wanted’ in French…

### PR DESCRIPTION
**Pull request by lucasfrey**
...Also correct some typo and errors on the first project.

### CODE REVIEW

**Comment by rik-cross** [comment]
Thanks @lucasfrey - I just added a missing comma to the manifest (see https://github.com/RaspberryPiFoundation/webdev-curriculum/commit/149baf2ca97e4625b9b62233d75a40a7fc3ffdd5). :)

**Comment by Matella15** [comment]
Hi @lucasfrey, thanks for all your work translating and checking projects! I just wanted to check in to ask if you're currently working on any HTML term 1 projects? We have a professional service that's going to help us get all our French projects translated over the next month and I want to make sure we're not duplicating any work.

**Comment by lucasfrey** [comment]
Hi @Matella15,

I am in the process of finishing the recipe project. I already translated the lesson I just need to get the pictures translated and I'll be able to make a pull request. I should be able to do that over easter week-end.

**Comment by Matella15** [comment]
@lucasfrey Thanks for the update and for translating the Recipe project. It looks great, hopefully we can get it up on the site over the next few days!  

We have a translator planning to work on HTML term 2, and our 2 Python terms, but do you think you would be able to continue work to translate the rest of HTML term 1 over the next 2-3 weeks? That would be about 1 project a week and would be a big help!

**Comment by lucasfrey** [comment]
@Matella15 Still happy to help :)

There is only 2 more projects on the HTML term 1 so I reckon that can be done in the next 2-3 weeks. I'll keep you guys in touch.

**Pull request merged**
